'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

type Vacancy = { vacancy_id: number; title: string; description: string; vacancy_type: string; opening_date: string; closing_date: string };
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://127.0.0.1:8000/api';

export default function ApplyPage() {
  const { id } = useParams<{ id: string }>();
  const [vacancy, setVacancy] = useState<Vacancy | null>(null);
  const [form, setForm] = useState({ nic: '', name: '', email: '', phone: '', address: '' });
  const [cv, setCv] = useState<File | null>(null);
  const [message, setMessage] = useState('');
  const [loadError, setLoadError] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => { fetch(`${API}/vacancies/${id}`).then(async (r) => { const p = await r.json().catch(() => ({})); if (!r.ok || !p.vacancy) { setLoadError(true); return; } setVacancy(p.vacancy); }).catch(() => setLoadError(true)); }, [id]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!cv) { setMessage('Please attach your CV as a PDF or Word document.'); return; } const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); body.append('cv', cv); const response = await fetch(`${API}/vacancies/${id}/applications`, { method: 'POST', body }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setMessage(payload.message ?? 'Unable to submit application.'); return; } setSubmitted(true); setMessage(`Application submitted successfully. Reference: ${payload.application_id}`); }
  if (!vacancy) return <main className="public-vacancies"><section className="vacancy-unavailable"><div className="dashboard-card__icon">!</div><h1>{loadError ? 'Vacancy unavailable' : 'Loading vacancy…'}</h1><p>{loadError ? 'This vacancy may have closed or is no longer available. Please return to the current vacancies list.' : 'Please wait while we load the vacancy details.'}</p>{loadError && <a className="vacancy-apply" href="/vacancies">← View current vacancies</a>}</section></main>;
  return <main className="public-vacancies"><header className="public-header"><a href="/vacancies" className="public-brand"><img src="/cpstl-logo.png" alt="CPSTL logo" /><span><strong>Ceylon Petroleum Storage Terminals Limited</strong><small>Recruitment Management System</small></span></a><a className="staff-login" href="/vacancies">← All vacancies</a></header><section className="vacancy-hero vacancy-hero--compact"><p className="eyebrow">CPSTL career opportunity</p><h1>{vacancy.title}</h1><p>{vacancy.vacancy_type} · Applications close {vacancy.closing_date}</p></section><section className="application-content"><div className="application-description"><p className="eyebrow eyebrow--red">Role overview</p><h2>{vacancy.title}</h2><p>{vacancy.description}</p></div>{submitted ? <div className="application-success"><div className="dashboard-card__icon">✓</div><h2>Application received</h2><p>{message}</p><a className="vacancy-apply" href="/vacancies">Return to vacancies <span>→</span></a></div> : <form className="application-form" onSubmit={submit}><h2>Submit your application</h2><p>Complete your details and attach your CV to apply.</p><input required placeholder="NIC number" value={form.nic} onChange={(e) => setForm({ ...form, nic: e.target.value })} /><input required placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input required type="email" placeholder="Email address" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input required placeholder="Phone number" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><textarea required placeholder="Address" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /><label className="cv-upload">CV (PDF, DOC or DOCX)<input required type="file" accept=".pdf,.doc,.docx" onChange={(e) => setCv(e.target.files?.[0] ?? null)} /></label><button className="vacancy-apply" type="submit">Submit application <span>→</span></button>{message && <p className="form-message form-message--error">{message}</p>}</form>}</section><footer className="public-footer">© {new Date().getFullYear()} CPSTL · Ceylon Petroleum Storage Terminals Limited</footer></main>;
}
