'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import DashboardNavigation from '@/components/dashboard-navigation';
import { useRmsUser } from '@/lib/use-rms-user';

type User = { name: string; roles: string[] };
type Notification = { notification_id: number; notification_type: string; recipient_email: string; subject: string; message: string; sent_at: string; candidate_name: string; vacancy_title: string };
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://127.0.0.1:8000/api';

export default function NotificationsPage() {
  const router = useRouter();
  const user = useRmsUser<User>();
  const [items, setItems] = useState<Notification[]>([]);
  const [error, setError] = useState('');

  useEffect(() => {
    if (user === undefined) return;
    if (user === null) { router.replace('/'); return; }
    fetch(`${API}/notifications`, { headers: { 'X-User-Role': user.roles[0] } }).then(async (response) => {
      const payload = await response.json().catch(() => ({})) as { notifications?: Notification[]; message?: string };
      if (response.ok) setItems(payload.notifications ?? []);
      else setError(payload.message ?? 'Unable to load notifications.');
    });
  }, [router, user]);

  if (!user) return <main className="dashboard-loading">Loading notifications…</main>;

  return <main className="dashboard-page"><div className="app-wrapper rms-adminlte">
    <DashboardNavigation roles={user.roles} />
    <section className="app-main"><header className="app-header"><span className="app-header__title">Candidate notifications</span><span className="app-header__meta">{user.name}<button className="dashboard-signout" type="button" onClick={() => { sessionStorage.removeItem('rms_user'); router.replace('/'); }}>Sign out</button></span></header><div className="content-wrapper">
      <div className="content-header"><div><h2>Notifications</h2><p>Appointment and application updates generated by the recruitment workflow.</p></div><div className="role-badge"><span className="role-badge__dot" />{items.length} records</div></div>
      {error && <p className="form-message form-message--error">{error}</p>}
      <section className="dashboard-panel"><div className="notification-list">{items.map((item) => <article className="notification-row" key={item.notification_id}><div className={`notification-icon ${item.notification_type === 'Appointment' ? 'notification-icon--success' : ''}`}>{item.notification_type === 'Appointment' ? '✓' : '!'}</div><div className="notification-info"><div className="application-row__heading"><h3>{item.subject}</h3><span className="workflow-status">{item.notification_type}</span></div><p><strong>{item.candidate_name}</strong> · {item.vacancy_title} · {item.recipient_email}</p><small>{item.message}</small><time>{item.sent_at ? new Date(item.sent_at).toLocaleString() : 'Pending'}</time></div></article>)}</div>{items.length === 0 && <div className="vacancy-empty">No candidate notifications have been generated yet. Notifications appear after HR closes an approved vacancy.</div>}</section>
    </div></section>
  </div></main>;
}
